// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repositories

import (
	"database/sql"
)

type Attempt struct {
	ID         string         `json:"id"`
	UserID     sql.NullString `json:"user_id"`
	SentenceID sql.NullString `json:"sentence_id"`
	UserInput  string         `json:"user_input"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	Evaluation sql.NullString `json:"evaluation"`
}

type LearnerProfile struct {
	UserID        string          `json:"user_id"`
	Theta         sql.NullFloat64 `json:"theta"`
	CefrLevel     sql.NullString  `json:"cefr_level"`
	VocabMap      sql.NullString  `json:"vocab_map"`
	GrammarMap    sql.NullString  `json:"grammar_map"`
	PragmaticsMap sql.NullString  `json:"pragmatics_map"`
}

type Sentence struct {
	ID         string         `json:"id"`
	TextNative string         `json:"text_native"`
	TextTarget sql.NullString `json:"text_target"`
	CefrLevel  sql.NullString `json:"cefr_level"`
	Topic      sql.NullString `json:"topic"`
	Tags       sql.NullString `json:"tags"`
}

type User struct {
	ID         string `json:"id"`
	Email      string `json:"email"`
	NativeLang string `json:"native_lang"`
	TargetLang string `json:"target_lang"`
}
