// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repositories

import (
	"context"
	"database/sql"
)

type Querier interface {
	FindAttemptByID(ctx context.Context, id string) (Attempt, error)
	FindAttemptByUserAndSentence(ctx context.Context, arg FindAttemptByUserAndSentenceParams) (Attempt, error)
	FindLearnerProfileByUserID(ctx context.Context, userID string) (LearnerProfile, error)
	FindNextSentenceForUser(ctx context.Context, cefrLevel sql.NullString) (Sentence, error)
	FindSentenceByID(ctx context.Context, id string) (Sentence, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	FindUserByID(ctx context.Context, id string) (User, error)
	// Attempt queries
	SaveAttempt(ctx context.Context, arg SaveAttemptParams) error
	// LearnerProfile queries
	SaveLearnerProfile(ctx context.Context, arg SaveLearnerProfileParams) error
	// Sentence queries
	SaveSentence(ctx context.Context, arg SaveSentenceParams) error
	// User queries
	SaveUser(ctx context.Context, arg SaveUserParams) error
}

var _ Querier = (*Queries)(nil)
